
package com.formasdigitales.timbrado40_ejemplo.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSTimbradoCFDIService", targetNamespace = "http://wservicios/", wsdlLocation = "http://dev33.facturacfdi.mx/WSTimbradoCFDIService?wsdl")
public class WSTimbradoCFDIService
    extends Service
{

    private final static URL WSTIMBRADOCFDISERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTIMBRADOCFDISERVICE_EXCEPTION;
    private final static QName WSTIMBRADOCFDISERVICE_QNAME = new QName("http://wservicios/", "WSTimbradoCFDIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev33.facturacfdi.mx/WSTimbradoCFDIService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTIMBRADOCFDISERVICE_WSDL_LOCATION = url;
        WSTIMBRADOCFDISERVICE_EXCEPTION = e;
    }

    public WSTimbradoCFDIService() {
        super(__getWsdlLocation(), WSTIMBRADOCFDISERVICE_QNAME);
    }

    public WSTimbradoCFDIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTIMBRADOCFDISERVICE_QNAME, features);
    }

    public WSTimbradoCFDIService(URL wsdlLocation) {
        super(wsdlLocation, WSTIMBRADOCFDISERVICE_QNAME);
    }

    public WSTimbradoCFDIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTIMBRADOCFDISERVICE_QNAME, features);
    }

    public WSTimbradoCFDIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTimbradoCFDIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSTimbradoCFDI
     */
    @WebEndpoint(name = "WSTimbradoCFDIPort")
    public WSTimbradoCFDI getWSTimbradoCFDIPort() {
        return super.getPort(new QName("http://wservicios/", "WSTimbradoCFDIPort"), WSTimbradoCFDI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTimbradoCFDI
     */
    @WebEndpoint(name = "WSTimbradoCFDIPort")
    public WSTimbradoCFDI getWSTimbradoCFDIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wservicios/", "WSTimbradoCFDIPort"), WSTimbradoCFDI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTIMBRADOCFDISERVICE_EXCEPTION!= null) {
            throw WSTIMBRADOCFDISERVICE_EXCEPTION;
        }
        return WSTIMBRADOCFDISERVICE_WSDL_LOCATION;
    }

}
